### ISSUE TITLE
[logstash-1.4.1] Trouble parsing csv _csvparsefailure exception=>#<CSV::MalformedCSVError: Illegal quoting in line

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-filter-csv#11]
(This issue was originally filed by @bpesics at https://github.com/elastic/logstash/issues/1908)

---

The csv filter fails to parse a message and does not provide information on what is the problem with the input text.

logstash version and os:
```
logstash-contrib-1.4.1-1_6e42745.noarch
logstash-1.4.1-1_bd507eb.noarch

CentOS release 6.5 (Final)
```

the configuration:
```
input {
  file {
    path           => ["/path/to/testfile"]
    start_position => "beginning"
    codec          => plain {
      charset      => "UTF-8"
    }
  }
}

filter {
    csv {
      separator => ",,,,"
      columns   => [ "db_host", "start_time", "user_host", "query_time", "lock_time", "sql_text", "db" ]
    }
}

output {
  stdout { codec => rubydebug }
}
```

the error message:
```
Trouble parsing csv {:source=>"message", :raw=>"
....
:exception=>#<CSV::MalformedCSVError: Illegal quoting in line 1.>, :level=>:warn}
````
````
...
      "@version" => "1",
    "@timestamp" => "2014-10-16T16:09:14.559Z",
          "host" => "some.domain.tld",
          "path" => "/path/to/testfile",
          "tags" => [
        [0] "_csvparsefailure"
    ]
}
````

the content of the test file can be found here: https://gist.githubusercontent.com/bpesics/a2af6e6b585499081de5/raw/bdbda0cf4bbde052d33307854f72f2d788631b00/gistfile1.txt

**Comment by duylong** [comment]
Same problem when I have a "" in a field. For example: 

```
...,nodeSelectListener="#{Control.selectListener}": java.lang.IllegalStateException: No tree element available or row key not set!
```

```
csv {
        source => "short_message"
        columns => [..., app_message]
        separator => ";"
}
```

**Comment by jordansissel** [comment]
@duylong your csv doesn't look valid. I don't think you can have a quote within an unquoted value. RFC4180 doesn't permit it. What specification are you using to generate your CSV?

**Comment by duylong** [comment]
Hmmm, I'm not use specification. We create it ourselves.

**Comment by jordansissel** [comment]
@duylong ahh, ok cool :)

I might suggest that your CSV is not valid, then? I believe this should be valid:

```
...,"nodeSelectListener=""#{Control.selectListener}"": java.lang.IllegalStateException: No tree ..."
```

**Comment by purbon** [comment]
closing this for now as a non valid CSV input is being send, we can always reopen if this surfaces a bug in our CSV library.

**Comment by manzoor77** [comment]
Error parsing csv {:field=>"message", :source=>"```\",\"\",\"{'\"disable_group_highlight'\": true}\",\"\",[],[],f,0,f,", :exception=>#<CSV::MalformedCSVError: Illegal quoting in line 1.>}
facing this issue

input {
  file {
    path => "/Users/manzoorfaisal/Desktop/Laptop-Migration-2/logstash-7.17.4/production-posts-test.csv"
   start_position => "beginning"
   sincedb_path => "/dev/null"
  type => "doc"
   #skip_header => true
   #source => "message"

  }
}
filter {
  # Add your filters here
  csv{
    separator=> ","
    columns=>["id","createat","updateat","deleteat","userid","channelid","rootid","originalid","message","type","props","hashtags","filenames","fileids","hasreactions","editat","ispinned","remoteid"]
   # columns=>["id","name","displayname","description","createat","updateat","deleteat","permissions","schememanaged","builtin"]

skip_header => true
  }

  mutate {
    remove_field => ["updateat","deleteat", "rootid","originalid","props","filenames","fileids","hasreactions","editat", "ispinned", "remoteid", "@timestamp","@version","host","path"]
  add_field => {
      "teamid" => "new_value"
    }
  }
}

output {
  elasticsearch {
    hosts => ["localhost:9200"]
    index => "production-post-index-01"
    document_id => "%{id}"

    #flush_size => 10
    #max_bulk_bytes => 9999999
    #template => "/Users/manzoorfaisal/Desktop/Laptop-Migration-2/logstash-7.17.4/config/posts_mapping.json"
    #template_name => "your_template_name"
    #template_overwrite => true
  }

  stdout{codec => rubydebug }
}
