### ISSUE TITLE
should have option for reading first event as header

### ISSUE THREAD

**Issue by andrewvc** [logstash-plugins/logstash-filter-csv#13]
The CSV filter should have an option to treat the first row as header. This would be useful for using it as an ETL tool.

Additionally, it could then ignore all subsequent rows that have that same exact value (extra header rows)

**Comment by dadoonet** [comment]
+1

**Comment by kurtado** [comment]
More discussion on csv-ish stuff here:
https://github.com/elastic/logstash/issues/2088

**Comment by purbon** [comment]
@andrewvc @dadoonet @kurtado I'm more towards implementing something alike with the proposal in https://github.com/elastic/logstash/issues/2088, the filter is reasonable as it's, so event based and not file based.

**Comment by dadoonet** [comment]
Agreed @purbon. IMO csv should not be a filter but a codec.
Same for `xml` BTW. It should be a codec.

**Comment by purbon** [comment]
@dadoonet agree, will do some work on making csv a codec, there we can include some state to keep track of headers, for example.

**Comment by purbon** [comment]
Closing this in favor of implementing a more general strategy as commented in https://github.com/elastic/logstash/issues/2088
