### ISSUE TITLE
CSV filter mutates the event's source field

### ISSUE THREAD

**Issue by PhaedrusTheGreek** [logstash-plugins/logstash-filter-csv#15]
"message" field is being converted to an array like this by the CSV filter.   

{
       "message" => [
        [0] "test"
    ], 
      "field1" => "test"
      "@version" => "1",
    "@timestamp" => "2015-09-09T16:35:39.086Z",
}

Without the CSV filter in place, the output is like this:

{
     "message" => "test",
      "@version" => "1",
    "@timestamp" => "2015-09-09T16:35:39.086Z",
}

Appears that the @source field is being mutated:
https://github.com/logstash-plugins/logstash-filter-csv/blob/master/lib/logstash/filters/csv.rb#L55-L66

**Comment by purbon** [comment]
Fixed in #18

**Comment by purbon** [comment]
closing this as #18 got merged.
