### ISSUE TITLE
Issues with numerical values that contain commas

### ISSUE THREAD

**Issue by sirmodok** [logstash-plugins/logstash-filter-csv#16]
When I use the csv filter to parse a large CSV file, I see some issues where numerical values that contain a comma break the parsing despite being in double quotes. 
My filter looks something like this

```
filter {
  if [type] == "nexpose" {
    # Uses the csv plugin to parse information from a CSV file into elasticsearch
    csv {
      columns => ["color", "shoe", "model", "Asset Risk Score","horses name","Asset OS Name", "small number", "fav ghostbuster" [...]
      separator => ","
    }
    grok {
      match => {"color" => "%{TIME:timestamp2}Z %{HOSTNAME:host} %{GREEDYDATA:colour}"}
    }
   # remove some useless fields
    mutate {
      remove_field => [ "timestamp2", "color" ]
    }
    # Drop the top row of the CSV file
    if [shoe] == "shoe" { drop{ } }
  }
}
```

If I feed it a CSV that contains a line that looks like this

```
purple,nike,Heidi Klum,"133,327","Microsoft Windows Server 2008 R2, Standard Edition",America,23,Venkman
```

Then in the results for the field "Asset Risk Score" will be "133" and not "133,327" even if the result for the field "Asset OS Name" is correctly "Microsoft Windows Server 2008 R2, Standard Edition"

![image](https://cloud.githubusercontent.com/assets/6287669/10773170/e4dcc57a-7cc7-11e5-80d7-79ad598a3cf6.png)

Both values are in double quotes, the only difference is that one is numerical and the other is a string. 

Here is an example from the logstash logs viewpoint
![image](https://cloud.githubusercontent.com/assets/6287669/10773763/487dca5e-7ccb-11e5-815c-3dd63a7757f2.png)

Has anyone else seen anything like this?

**Comment by purbon** [comment]
@sirmodok I just tested your issue in isolation of the CSV filter, mostly using this rspec tests

```
  # Use a more rspec3 syntax, avoiding the usage of sample
  # and insist in favor of rspec helpers methods
  describe LogStash::Filters::CSV  do

    subject(:plugin) { LogStash::Filters::CSV.new(config) }
    let(:config) { Hash.new }

    let(:doc) { ""}
    let(:event) { LogStash::Event.new("message" => doc) }


    before(:each) do
      plugin.register
    end

    describe "using a separator" do

      let(:doc) { 'purple,nike,Heidi Klum,"133,327","Microsoft Windows Server 2008 R2, Standard Edition",America,23' }

      let(:config) do
        { "columns" => ["color", "shoe", "model", "Asset Risk Score","horses name","Asset OS Name", "small number", "fav ghostbuster"], 
          "separator" => "," }
      end
      it "should parse numbers without truncation" do
        plugin.filter(event)
        expect(event["Asset Risk Score"]).to eq("133,327")
      end
    end
  end
```

this show up no issue on my side, so I wonder if there are external implications. can you test this again with the last release? on the other side which OS are you using? and JVM?

**Comment by purbon** [comment]
@sirmodok tested also with the last logstash (master) in a mac and the last csv plugin, output is

```
skywalker% ./bin/logstash -f dummy.conf               
Settings: Default filter workers: 2
Logstash startup completed
purple,nike,Heidi Klum,"133,327","Microsoft Windows Server 2008 R2, Standard Edition",America,23,Venkman
{
             "message" => [
        [0] "purple,nike,Heidi Klum,\"133,327\",\"Microsoft Windows Server 2008 R2, Standard Edition\",America,23,Venkman"
    ],
            "@version" => "1",
          "@timestamp" => "2015-11-30T19:01:53.953Z",
                "host" => "0.0.0.0",
                "shoe" => "nike",
               "model" => "Heidi Klum",
    "Asset Risk Score" => "133,327",
         "horses name" => "Microsoft Windows Server 2008 R2, Standard Edition",
       "Asset OS Name" => "America",
        "small number" => "23",
     "fav ghostbuster" => "Venkman",
                "tags" => [
        [0] "_grokparsefailure"
    ]
}
```

using your own example line and config, so I this makes me believe this is a no issue for now. Closing this for now, feel free to reopen if you got more intel on this issue.

Thanks a lot for your report.

**Comment by sirmodok** [comment]
I guess my issue stems from not knowing how to install the plugin. 
If I use "plugin install logstash-filter-csv" then version 1.0.0 installs. 
"plugin update logstash-filter-csv" updates to version 1.0.0.

I read the README you have included, however it only has some generic instructions which do not appear to apply. 

Following said generic instructions, I used git clone to copy the directory down and attempted to install the plugin using "plugin install /path/to/logstash-filter-csv.gem" however I am unable to find an actual gem file in the directory so the install bombs out. 

Thanks, It turns out I had an older version of logstash installed. I thought I had updated in previously, but I guess I was wrong. As a result the plugin manager would not install the latest version of the logstash-filter-csv.

**Comment by sirmodok** [comment]
I spoke too soon. 
After updating logstash and the csv filter I am still seeing the same results. 
I am currently running 

Logstash 2.1.0
Red Hat Enterprise Linux Server release 6.6 (Santiago)
java version "1.7.0_79"

Here is an example alert. 
You can see in the message field \"89,182\" however in the results you see "Asset Risk Score" => 89,

![image](https://cloud.githubusercontent.com/assets/6287669/11486126/a130ab28-977c-11e5-87f8-bb2211a4fbf7.png)

Tomorrow I am going to stand up a new ELK server from scratch and see if I can replicate the issue on a fresh machine.

**Comment by purbon** [comment]
@sirmodok this is very strange to me, it looks like if you got a mutate going on somehow that convert it to integer. Let me know if you find more intel on it.

**Comment by sirmodok** [comment]
I figured out what my issue was, although I have not figured out how to fix it. 
In my stack of config files I also have this config that catches specific values and converts them to the proper format. 

For example  "Asset Risk Score" comes in as a string, but in order to manipulate the data properly I would like it to be an integer.
 
So I have a filter called "80-convert-filter" that contains the line 
`filter {
  mutate {
    convert => [ "Asset Risk Score", "integer" ]
  }
}`

CSV filter parses the data correctly, however when the filter config converts the data from string to number, it drops everything after the first comma. 
I know convert filter is not yours, but do you have any ideas?

Is it possible to declare the format type while the CSV is being parsed?

**Comment by purbon** [comment]
I see, my feeling were correct, there is a mutate doing the nasty job there. happy to help. Speaking about CSV type conversions it will be there when https://github.com/logstash-plugins/logstash-filter-csv/pull/19 gets merged.

BTW, mutate will let you use ```float``` as type :+1:

**Comment by sirmodok** [comment]
Thanks. I did try float and got the same result. If I understand correctly float values are for storing decimals not long numbers.

**Comment by purbon** [comment]
yes, I think you will get a ton of benefit to ask questions at https://discuss.elastic.co/ there are a lot of very helpful folks (including us) that will help with your issues.

**Comment by sirmodok** [comment]
I want to thank you so much for your help. I was able to fix the issue by adding some mutate { gsub stuff to my conversion file so that all commas were stripped out of the field before attempting to convert to integer. 
:+1:
