### ISSUE TITLE
"error"=>{"type"=>"mapper_parsing_exception" when parsing an IP address

### ISSUE THREAD

**Issue by sirmodok** [logstash-plugins/logstash-filter-csv#21]
The csv file that I am parsing contains fields that contain IP addresses. 
I had an issue previously with long numbers with commas in them which I resolved by updating to the latest version of everything, so I'm up to date. 

Here is the full excerpt

```
"_id"=>"AVFpLcWcrpgg0aNvK1oM", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse [Asset IP Address]", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"Invalid format: \"192.168.1.166\" is malformed at \".168.1.166\""}}}}, :level=>:warn}
```
It looks like it takes the first octet then bombs out. 

My config looks like this 
```
[ me on yakul :] cat 26-nexpose-filter.conf
filter {
  if [type] == "nexpose" {
    # Uses the csv plugin to parse information from the Nexpose csv file into elasticsearch
    csv {
      columns => ["Site Name", "Asset IP Address", "Asset Names", "Asset Risk Score", "Asset OS Family", "Asset OS Name", "Asset OS Version", "Vulnerability Title", "Vulnerability Severity Level", "Vulnerability Risk Score", "Vulnerability Test Date", "Vulnerability CVSS Score" ]
      separator => ","
    }
    grok {
      match => {"Site Name" => "%{TIME:timestamp2}Z %{HOSTNAME:host} %{GREEDYDATA:Site}"}
    }
   # remove some useless fields
    mutate {
      remove_field => [ "timestamp2", "Site Name" ]
    }
   # Drop the top row of the CSV file
    if [Asset Names] == "Asset Names" { drop{ } }
  }
}
```

And an example of the input 

Site Name|Asset IP Address|Asset Names|Asset Risk Score|Asset OS Family|Asset OS Name|Asset OS Version|Vulnerability Title|Vulnerability Severity Level|Vulnerability Risk Score|Vulnerability Test Date|Vulnerability CVSS Score
---|---|---|---|---|---|---|---|---|---|---|---
This freaking site|192.168.1.166|computer.name|12,338|Microsoft Windows|That one thats a server|SP1|it can be hax0red|8|733|11/15/2015|7.5

More details:
```
[ me on yakul :] bin/elasticsearch --version
Version: 2.0.0, Build: de54438/2015-10-22T08:09:48Z, JVM: 1.7.0_79

[ me on yakul :] bin/logstash --version
logstash 2.0.0

[ me on yakul :] bin/plugin list --verbose | grep logstash-filter-csv
logstash-filter-csv (2.0.2)
```

Whenever I remove the IP address field it seems to behave better. 
```
"2015-12-03T19:27:39.448Z server.server.com This freaking site,computer.name,\"12,338\",Microsoft Windows,That one thats a server,SP1,it can be hax0red,8,733,2015-11-15,7.5"
    ],
                        "@version" => "1",
                      "@timestamp" => "2015-12-03T19:27:43.843Z",
                            "type" => "nexpose",
                       "Site Name" => "2015-12-03T19:27:39.448Z server.server.com This freaking site",
                     "Asset Names" => "computer.name",
                "Asset Risk Score" => 12338,
                 "Asset OS Family" => "Microsoft Windows",
                   "Asset OS Name" => "That one thats a server",
                "Asset OS Version" => "SP1",
             "Vulnerability Title" => "it can be hax0red",
    "Vulnerability Severity Level" => 8,
        "Vulnerability Risk Score" => 733,
         "Vulnerability Test Date" => "2015-11-15",
        "Vulnerability CVSS Score" => 75,
                      "timestamp2" => "19:27:39.448",
                            "host" => "server.server.com",
                            "Site" => "This freaking site"
```

And finally I have a logstash config file that does some conversions that looks like this. 
```
# This filter is a catch all for some fields that need to be identified as numbers and not strings.
# Removes commas from strings that will soon be converted to numbers
filter {
  mutate {
    gsub => [ "Asset Risk Score", "\D", "" ]
    gsub => [ "Vulnerability Risk Score", "\D", "" ]
    gsub => [ "Vulnerability Severity Level", "\D", "" ]
  }
# converting specific fields to the proper format
  mutate {
    convert => [ "source_port", "integer" ]
    convert => [ "destination_port", "integer" ]
    convert => [ "last_check_num", "integer" ]
    convert => [ "Asset Risk Score", "integer" ]
    convert => [ "Vulnerability Risk Score", "integer" ]
    convert => [ "Vulnerability Severity Level", "integer" ]
    convert => [ "Vulnerability CVSS Score", "float" ]
  }
}
```

It doesn't apply any changes to the IP address field so I don't know if it has anything to do with it, however I figured I would include it just for full disclosure. 

Thanks in advance.

**Comment by jordansissel** [comment]
This sounds like an Elasticsearch mapping problem - "reason"=>"Invalid format: \"192.168.1.166\" is malformed at \".168.1.166\""}

Can you ask on elastic.discuss.co?  If I had to guess, Elasticsearch has your field mapped as a double or float, based on the error. Attach your index mapping when you ask this on elastic.discuss.co and we should be able to get you some help :)

**Comment by sirmodok** [comment]
I didn't see this comment until now. 
Although I do not know what the full issue was, you are probably correct. When I moved by logstash instance to production from test, it all started functioning properly. 

Sorry to bug you guys again.

**Comment by blaker00** [comment]
I'm having the same issue...


logstash;

        if [type] == "paloalto" and [SourceIP] !~ "(^127\.0\.0\.1)|(^10\.)|(^172\.1[6-9]\.)|(^172\.3[0-1]\.)|(^192\.168..)|(^169\.254\.)" {

                        geoip {
                                source => "SourceIP"
                                target => "geoipsrc"
                                database => "/etc/logstash/GeoLiteCity.dat"
                                add_field => [ "[geoipsrc][coordinates]", "%{[geoipsrc][longitude]}" ]
                                add_field => [ "[geoipsrc][coordinates]", "%{[geoipsrc][latitude]}"  ]
                        }
                        mutate {
                                convert => [ "[geoipsrc][coordinates]", "float"]
                        }
                }

elasticsearch:


 "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse [geoipsrc.ip]", "caused_by"=>{"type"=>"number_format_exception", "reason"=>"For input string: \"93.189.26.18\""}}}}, :level=>:warn}


This is being mapped as type IP:


 "geoipsrc" : {
            "properties" : {
              "area_code" : {
                "type" : "long"
              },
              "city_name" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "continent_code" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "coordinates" : {
                "type" : "double"
              },
              "country_code2" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "country_code3" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "country_name" : {
                "type" : "string",
                "index" : "not_analyzed"
              },
              "dma_code" : {
                "type" : "long"
              },
              "ip" : {
           **      "type" : "ip"**
              },
              "latitude" : {
                "type" : "double"
              },
              "location" : {
                "type" : "double"
              },
