### ISSUE TITLE
Convert example is incorrect

### ISSUE THREAD

**Issue by nostrebor** [logstash-plugins/logstash-filter-csv#42]
The example at

https://www.elastic.co/guide/en/logstash/current/plugins-filters-csv.html#plugins-filters-csv-convert

does not work. The fields to convert are comma separated rather than on separate lines.

**Comment by magnusbaeck** [comment]
This is a duplicate of #28. While the source has been corrected the documentation on www.elastic.co lags behind.

**Comment by jsvd** [comment]
This has been solved since v3.0.3. thanks all
