### ISSUE TITLE
Skip header option within csv filter

### ISSUE THREAD

**Issue by AbdulHaseebHussain** [logstash-plugins/logstash-filter-csv#58]
Would it be possible to have an option for users to skip header lines should they wish to, similar to the autogenerate_column_names boolean option. Users generally implement this functionality themselves.

 Could the drop filter plugin be called automatically if the skip header option is specified?

**Comment by tomrade** [comment]
I use the "exclude" option in filebeat for w3c files, but something similar could be nice here

**Comment by guyboertje** [comment]
Closing because #59
