### ISSUE TITLE
CSV parsing empty fields

### ISSUE THREAD

**Issue by jordansissel** [logstash-plugins/logstash-filter-csv#9]
(This issue was originally filed by @t1nkerer at https://github.com/elastic/logstash/issues/2099)

---

Hello,

How can I remove empty fields from log entry when parsing csv file? I have diverse range of log files with fixed number of columns that may be empty. As a result I get:

"destinationHostName": "",

 in my elasticsearch.

Although it is empty I cannot use _exists_ anymore because the field is there.

Is there an easy way to do this or do I have to check all the fields for empty values and remove them one by one?

**Comment by purbon** [comment]
This could be fix by the new ```skip_empty_columns``` config option just added today in master, check https://github.com/logstash-plugins/logstash-filter-csv/blob/master/lib/logstash/filters/csv.rb#L43-L45 for more details.

A new version with this feature will be released soon, stay tuned to this issue and others.

@t1nkerer
